### PR TITLE
Alerts

### PR DESCRIPTION
**Pull request by fabiand**
Add some basic prom alert

### CODE REVIEW

**Review by fabiand — COMMENTED** [review]
@enp0s3 please review

**Comment by enp0s3** [comment]
@fabiand Would be interesting to test whether the metric collection remains stable when the node in subject is thrashing

**Comment by fabiand** [comment]
> @fabiand Would be interesting to test whether the metric collection remains stable when the node in subject is thrashing

I'd expect so if the kubelet (what I assume) is erporting the metrics, because the kubelet.service is part of the system.slice, which is ) not swapping and b) has better latency guarantees.

**Comment by enp0s3** [comment]
> [@fabiand ](/fabiand)
> ` [alert](/fabiand/wasp-operator-prototype/pull/3/commits/2e55ca179ece455d41fd2d5354ba0c8714928b2d)`

I was thinking that [node exporter](https://github.com/prometheus/node_exporter/blob/09014c0c5ca7d24bbad09e821efe6c676702f12f/collector/meminfo_linux.go#L43) provides these metrics (probably by adding `node_memory_` prefix to whatever it sees in meminfo).
If this is the case then I hope node exporter would be responsive to prom. scrappers

**Pull request merged**
